# Dev環境のSAMスタック削除用ワークフロー
name: Pipeline-Dev-Delete

on:
  delete:
    branches:
      - 'dev**'

env:
  SAM_TEMPLATE: template.yaml
  DEV_SAM_CONFIG: samconfig/samconfig-dev.toml
  DEV_REGION: ap-northeast-1
  DEV_PIPELINE_EXECUTION_ROLE: arn:aws:iam::247574246160:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-6nHJDsLBsTX7
  DEV_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::247574246160:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-uWkYpf2NyLLU

permissions:
  id-token: write
  contents: read
jobs:
  delete-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the dev pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.DEV_REGION }}
          role-to-assume: ${{ env.DEV_PIPELINE_EXECUTION_ROLE }}
          role-session-name: dev-delete
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Delete dev branch stack
        run: |
          sam delete \
            --config-file ${DEV_SAM_CONFIG} \
            --no-prompts
